INSERT INTO team (name, acronym, budget) VALUES ('Monaco', 'OGCM', 5000000.0),
('Valborne', 'OGCV', 1000000.0),
('OGC Nice', 'OGCN', 2000000.0);
INSERT INTO player (name, position, team_id) VALUES
    ('Kasper Dolberg', 'Forward', 1),
    ('Amine Gouiri', 'Forward', 1),
    ('Messi Apate', 'Attacker', 1),
    ('Kylian Mbappe', 'Attacker', 1),
    ('Neymar Jr', 'Attacker', 1),
    ('Lionel Messi', 'Attacker', 1),
    ('Cristiano Ronaldo', 'Attacker', 1),
    ('Karim Benzema', 'Attacker', 1),
    ('Zinedine Zidane', 'Midfielder', 1),
    ('Paul Pogba', 'Midfielder', 1),
    ('Kasper Dolberg', 'Forward', 2),
    ('Amine Gouiri', 'Forward', 2),
    ('Mbape Dupont', 'Middle', 2),
    ('Antoine Giroud', 'Forward', 2),
    ('Kylian Mbappe', 'Attacker', 2),
    ('Neymar Jr', 'Attacker', 2),
    ('Lionel Messi', 'Attacker', 2),
    ('Cristiano Ronaldo', 'Attacker', 2),
    ('Karim Benzema', 'Attacker', 2),
    ('Zinedine Zidane', 'Midfielder', 2),
    ('Paul Pogba', 'Midfielder', 2);
